package com.messi.rbm.authsim.model;

/**
 * Represents an event generated by an RBM agent.
 *
 * @param eventId   unique identifier of the event.
 * @param eventType type of event reported.
 * @param messageId identifier of the related message.
 */
public record AgentEvent(
        String eventId,
        String eventType,
        String messageId
) {
}
